# Generated by Django 5.1.4 on 2025-01-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('battery', models.CharField(max_length=3)),
                ('ready', models.BooleanField()),
                ('condition', models.PositiveSmallIntegerField()),
                ('charge', models.DecimalField(decimal_places=1, max_digits=4)),
                ('rint', models.DecimalField(decimal_places=3, max_digits=5)),
                ('user', models.CharField(max_length=150)),
                ('memo', models.TextField()),
            ],
        ),
    ]
