# Generated by Django 5.1.4 on 2025-01-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='condition',
            field=models.CharField(choices=[('G', 'Good'), ('F', 'Fair'), ('P', 'Poor'), ('N', 'N/A')], default='N', max_length=1),
        ),
    ]
