# Generated by Django 5.1.4 on 2025-01-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_alter_entry_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='condition',
            field=models.PositiveSmallIntegerField(choices=[(0, 'N/A'), (3, 'Good'), (2, 'Fair'), (1, 'Poor')], default=0),
        ),
    ]
